name: VoltskiyaCustomMobs
version: 1.0
main: apple.voltskiya.custom_mobs.VoltskiyaPlugin
api-version: 1.19
authors: [ appleptr16 ]
softdepend: [ LoadDependencies, AppleConfigs, AppleMCUtil, DecodingNms, VoltskiyaUtilities, VoltskiyaMobManager ]
