name: VoltskiyaCustomMobs
version: 1.0
main: apple.voltskiya.custom_mobs.VoltskiyaPlugin
api-version: 1.16
authors: [ appleptr16 ]
softdepend: [ LuckPerms, LoadDependencies, VoltskiyaUtilities, DecodingNms ]